### ISSUE TITLE
Search GH on input

### ISSUE THREAD

**Issue by netromdk** [voidpirate/gh-first-commit#4]
If the user does not give a "complete" URL, i.e. not containing "http(s)://" for instance (and if it does then just do as you do already), then you could search GH for repositories by users and organisations. Possibly grouping the results like that as well.

For each result include a link that will invoke your routines for finding the first comment for the specific repository.

This will make it generally easier to use.

**Comment by voidpirate** [comment]
It's been implemented as such. Please note the search API endpoint has a stricter rate limit than the repo listing endpoint. The search is limited to 10 requests per minute (I think; reviewed the headers from the response and 60 seconds looks to be the rate limit refresh rate, couldn't find any info in the documentation)
